### ISSUE TITLE
Corrupted video with this stream

### ISSUE THREAD

**Issue by prof-membrane** [mapfau/inputstream.mpd#32]
http://akamai-progressive.irt.de/Interop/2015_11/1.5/16adapt/hbbtv_1.5_16adapt_3.mpd

The DashIF Player has no problem with this stream, but Kodi has problems decoding it via DVXA2/software. I'm not sure if this is an FFmpeg issue. I can provide screenshots if you can't reproduce the problem.

Inputstream.mpd 1.2.9, Kodi 17 Beta 1, Windows 7

**Comment by mapfau** [comment]
Reason is, that there is only one initialization fragment for all video streams (AdaptationSet).
Inside this init data segment we use avc codec data and it is 640x360. ffmpeg uses those values and because of that everything looks so ugly.

To solve this, modification of initdata::codec_extradata must be done. Possible, but I'll wait for this until the issue pops up in real live.

**Comment by mapfau** [comment]
https://github.com/mapfau/inputstream.mpd/commit/45b23b4bcc4a714182c1209e3039d52613753794
